DATASET:
  train_dataset: ShapeNet
  test_dataset: ShapeNet
  n_outpoints: 16384

CONST:
  num_workers: 32
  n_input_points: 3000

NETWORK:
  n_sampling_points: 2048 
  n_primitives: 32
  model_type: "MSN"
  metric: "emd"

TRAIN:
  learning_rate: 0.0001
  batch_size: 32
  n_epochs: 150
  save_freq: 5
  log_freq: 1

TEST:
  metric_name: "EMD"
